# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11b561d9771f58ba1a9c1a93db780ccade38983f4f5acc0e785d1b83e7ac511c3daf413d748685559483a48c6fa5a03c0501c7276a6a900e219b05cbb6c34aa6

test:
  secret_key_base: 8964306b645debf2486217861dc543d2fdbe33d94b475a1c5a7ede401f175adc62beb9f7a53896e55e4fec5153d7e0a704b6cda3f40bd753b07cc5863c380f4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
